#!/usr/bin/env bash
# The path to the file to be transferred.
# The IP of the server to transfer the file to.
# The username that scp connects with.
# The path to the SSH private key that scp uses. 

# Checking for command line arguments

if [ $# -lt 4 ]

then

  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

  exit 1

fi

# Assigning parameters to variables
path_to_files=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disabling strict host key checking
 scr -o "StrictHostKeyCkecking" -i "$path_to_ssh_key" "$path_to_file" "$username$ip:~/
 # Checking if the transfer was successful
 
 if [$? -eq o]
 then
	 echo "file was TRANSFERED SUCCESSFUL"
 else
	 echo "file TRANSFER FAILED"

fi

