#!/usr/bin/env bash
# Install HAproxy on clean ubuntu 20.04 machine and setup to proxy requests
# between web-01 and web-02.

apt-get update -y && \
apt-get install -y software-properties-common && \
add-apt-repository -y ppa:vbernat/haproxy-1.7 && \
apt-get update -y && \
apt-get install -y haproxy && \
if [ -e '/etc/haproxy/haproxy.cfg.orig' ]
then
    cat /etc/haproxy/haproxy.cfg.orig > /etc/haproxy/haproxy.cfg
else
    cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
fi
echo -e \
"\nlisten load_balancer
\tbind :80
\tmode http
\tstats enable
\tstats uri /haproxy?stats
\tbalance roundrobin
\tserver web-01 100.26.230.254:80 check
\tserver web-02 54.82.136.98:80 check" \
    >> /etc/haproxy/haproxy.cfg
service haproxy restart
