#!/usr/bin/env bash

# Script: my_script.sh
# # Description: This script displays the message "To infinity and beyond indefinitely"
# #              and handles SIGINT, SIGTERM, and SIGQUIT signals appropriately.
#
# # Function to handle SIGINT signal (Ctrl+C)
# function sigint_handler() {
#   echo "Y U no love me?!"
#   }
#
#   # Function to handle SIGTERM and SIGQUIT signals
#   function sigterm_quit_handler() {
#     echo "I hate the kill command"
#       rm /var/run/myscript.pid
#         exit
#         }
#
#         # Trap SIGINT signal and call sigint_handler function
#         trap sigint_handler SIGINT
#
#         # Trap SIGTERM and SIGQUIT signals and call sigterm_quit_handler function
#         trap sigterm_quit_handler SIGTERM SIGQUIT
#
#         # Get the PID of the current process
#         echo $$ > /var/run/myscript.pid
#
#         # Infinite loop to display the message "To infinity and beyond indefinitely"
#         while true
#         do
#           echo "To infinity and beyond indefinitely"
#             sleep 2
#             done
#
