#!/usr/bin/env bash

# Get the PID of the process named "7-highlander"
# pid=$(pgrep -f '7-highlander')
#
# # Check if the process exists and terminate it
# if [ -n "$pid" ]; then
#   kill "$pid"
#     echo "Process 7-highlander killed."
#     else
#       echo "Process 7-highlander not found."
#       fi
#
