#!/usr/bin/env bash
# Using while loop displays the content of the file /etc/passwd
# Only display script
# username
# User id
# Home directory path for the user

while IFS= read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
