#!/usr/bin/env bash
# Script that parses Apache logs
# The exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# In list format
# Ordered from the greatest to the lowest number of occurrences
# Must use awk

log_file="apache-access.log"

awk -F' ' '{ print $1 " " $9 }' "$log_file" | sort | uniq -c | sort -nr

