#!/usr/bin/env bash
# Using a while loop and case statement displays numbers that loops from 1 to 20 and
# Displays 4 and then bad luck from China for the 4th loop iteration
# Displays 9 and then bad luck from Japan for the 9th loop iteration
# Displays 17 and then bad luck from Italy for the 17th loop iteration

iteration=1

while [ $iteration -le 20 ]
do
  echo "$iteration"
  case $iteration in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( iteration++ ))
done
