#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

filename="school"

if [ -e "$filename" ]; then
  echo "$filename file exists"

  if [ -s "$filename" ]; then
    echo "$filename file is not empty"
  else
    echo "$filename file is empty"
  fi

  if [ -f "$filename" ]; then
    echo "$filename is a regular file"
  fi
else
  echo "$filename file does not exist"
fi
